#!/usr/bin/python
from Data.addNewPatients import *
from Data.assignData import *
from Data.sqlConnector import *

def test_addPatient():
    addNew = addNewPatients()
    list = patientList()
    p1 = Patient()
    db = myConnector()

    p1.setFirstName("Barry")
    p1.setMiddleName("Andrew")
    p1.setLastname("Matthews")
    p1.setAddress(["918 Main Road", "Huntsville", "Alabama", "35776"])
    p1.setHomePhone("555-123-4567")
    p1.setWorkPhone("555-456-7890")
    p1.setMobilePhone("555-789-0234")
    p1.addEmergencyContact("Emergency contact name 1", "555-233-4566")
    p1.addEmergencyContact("Emergency contact name two", "555-455-6788")
    p1.addEmergencyContact("Emergency contact name 3", "555-455-6788")
    p1.setNumAllowedVisitors("3")
    p1.addAllowedVisitor("Visitor 1")
    p1.addAllowedVisitor("Bob Jones")
    p1.addAllowedVisitor("George Washington")
    p1.addAllowedVisitor("Visitor 4")
    p1.setLocation(["Facility 7", "Floor 2", "Room 213", "Bed 1"])
    p1.setFamilyDoctor("Dr. Medical Doctor Man")
    p1.setDateAdmittance("January 17, 2020")
    p1.setTimeAdmittance("7:15PM")
    p1.setDateDischarge("April 2, 2020")
    p1.setTimeDischarge("8:20PM")
    p1.setReasonAdmission("Broken Arm")
    p1.addPrescription("Medicine 1", "15mg", "Every Morning")
    p1.addPrescription("Another Medicine", "3mg", "Every Night")
    p1.addScheduledProcedure("Surgery on leg at 3PM")
    p1.addScheduledProcedure("Another surgery at 5PM")
    p1.addDoctorNote("Patient needs medicine")
    p1.addDoctorNote("Patient is doing well")
    p1.addNurseNote("Patient had treatment at 7:15AM")
    p1.addNurseNote("Patient scheduled for surgery tomorrow")
    p1.setInsuranceCarrier("Big Insurance Company")
    p1.setInsuranceAccountNumber("123456789")
    p1.setInsuranceGroupNumber("987654")
    p1.setAmountPaid(481.1891024)
    p1.setAmountPaidByInsurance(15.81870)
    p1.addCharge("Broken leg repaired", 890.1333)
    p1.addCharge("Really long charge name that would need to be wrapped around to display properly without going off of the screen", 3101.31)
    p1.addCharge("Expensive Medicine administered", 443.145)
    
    addNew.newPatient(p1)

    list.createList()
    records = list.getList()
    assert records[len(records)-1].firstName == "Barry"
   
    db.execute("SET SQL_SAFE_UPDATES = 0;")
    db.execute("DELETE FROM patients WHERE home_phone='555-123-4567';")
    db.execute("SET SQL_SAFE_UPDATES = 1;")
    db.connection.commit()